### ISSUE TITLE
.+ syntax for hours

### ISSUE THREAD

**Issue by matthew-piziak** [m-cat/org-recur#1]
In regular Org-mode habit syntax, if I have `SCHEDULED: <2019-04-22 Mon 17:00 .+10h>`, the `.+` behaves like `+`. I believe this is a bug in Org mode specifically for hours syntax.

Does this package have a way to recreate the _desired functionality_, that is, a habit that gets put forward ten hours into the future, rather than ten hours after the existing timestamp?

**Comment by mrcnski** [comment]
I'm not sure I understand your first paragraph as I do not use org-habit. However, org-recur uses `org-schedule` internally, which unfortunately does not support `+10h` or the syntax you mention. There's not much I can do about this.

**Comment by matthew-piziak** [comment]
Got it, thanks.
