### ISSUE TITLE
[Feature Request] Adding support for deadline

### ISSUE THREAD

**Issue by god464** [m-cat/org-recur#11]
First at all, thank for this package, It helps me to plan my daily tasks better than before.

Now I would like to add support for deadlines to this package so that I can easily plan my daily tasks over a period of time without having to add them manually every day.

**Comment by mrcnski** [comment]
I'm happy the package has been useful for you! 😊

Adding support for deadlines is a great idea. Should be simple to do. I can try to get to it this week, but I can't promise anything.

**Comment by mrcnski** [comment]
@god464 What is your use case for this feature? I thought about it more, and to me, the idea of recurring deadlines seems odd. Also, how do you envision this feature working? Would it use the same recurrence syntax, and just a different command for updating the deadline?

**Comment by god464** [comment]
> What is your use case for this feature? I thought about it more, and to me, the idea of recurring deadlines seems odd. Also, how do you envision this feature working? Would it use the same recurrence syntax, and just a different command for updating the deadline?

Sorry for the late reply.  For example, I have an exam at Friday (assumed as 2023-3-19). I will write like this:
```org-mode
* TODO |+1| prepare for the Math exam
DEADLINE: <2023-03-10 Fri>
```
Before deadline, it will work like normally recurring task.  After the deadline is marked DONE, it will not be repeated as a normal task.

**Comment by mrcnski** [comment]
Thanks for the clarification! 

> Before deadline, it will work like normally recurring task.

If I understand you right, you want the task to be rescheduled on a daily basis? org-recur should already support this use-case -- it just won't touch the deadline. I've done this same thing before by adding the deadline and then completing the task manually.

org-recur doesn't really try to guess the user's intention in every scenario, it just aims to be a framework to quickly complete/reschedule daily tasks. Special cases require manual intervention, but shouldn't slow down the system too much. That said, do feel free to fork the repo if this feature is important to you! Feel free to re-open if you have any questions.
