### ISSUE TITLE
How can I use it to set up recurring tasks?

### ISSUE THREAD

**Issue by Prague2049** [m-cat/org-recur#12]
There is a todo task that you want to repeat every working day.
** |wkdy| ☞ TODO test
**  ☞ TODO |wkdy|  test
What is the correct setting?
I will switch the Todo label to Done when the task is done. Can it automatically change the duplicate task from Done to Todo?

**Comment by mrcnski** [comment]
Hello @Prague2049!

It is possible to have TODO states in a heading -- they are compatible with `org-recur`, though they are not necessary to have. If you wish to include a TODO state, it **must** appear **first** in the heading, or it will not be picked up by org-mode. So, the correct format would look like this:

```org
 ** TODO |wkdy| test
```

Note that `org-recur` does not have this limitation; the recurrence syntax (`|wkdy|`) can appear anywhere in the heading.

> I will switch the Todo label to Done when the task is done. Can it automatically change the duplicate task from Done to Todo?

I'm not sure what you're asking exactly, but `org-recur` does not touch TODO states, except when completing a one-off task. Apart from that, they need to be managed manually. i.e. `org-recur` does not try to guess how a TODO state should change for recurring tasks. This keeps the package simple and unopinionated.

Thanks for raising this issue, I'll update the readme.

**Comment by mrcnski** [comment]
README updated. Going to close, but please re-open if you have any questions!

**Comment by Prague2049** [comment]
Thanks！
When I set the following time period. 
** ☞ TODO |wkdy| test
SCHEDULED: <2023-03-16 Thu 08:00-11:00>

After I finish the task with d in agenda. Tomorrow's task becomes the following, but without the time period. 
** ☞ TODO |wkdy| test
SCHEDULED: <2023-03-17 Fri >
Is it possible to keep the original time period?
** ☞ TODO |wkdy| test
SCHEDULED: <2023-03-17 Fri 08:00-11:00>

**Comment by mrcnski** [comment]
Good question, will move into its own issue. 👍
