### ISSUE TITLE
"First wednesday of the month" ?

### ISSUE THREAD

**Issue by Trevoke** [m-cat/org-recur#2]
Hello! Does org-recur support the idea of doing "the first Wednesday of the month" or things like that? It seems like it might but I didn't find that in the documentation.

**Comment by mrcnski** [comment]
org-recur supports `org-schedule` syntax (which is its backend) as well as the ability to pick the *soonest* of several options. It doesn't seem like these can be combined in any way to get what you want. You could check out some [other solutions](https://stackoverflow.com/questions/16946220/emacs-org-mode-how-to-set-date-and-time-on-the-first-wednesday-of-month) which seem to allow for this.

**Comment by Trevoke** [comment]
Oh wow, I would not have gone that direction to look for a solution. Thank you!

**Comment by mrcnski** [comment]
No problem! Will add a note about this to the readme.
