### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by jsbmg** [m-cat/org-recur#6]
I'm using the exact configuration under "Recommended Configuration" in the readme.

In an agenda file, a heading like `* TODO  |+1| Do a thing` doesn't appear in my agenda. If I schedule that TODO for today, like this:

```
* TODO |+1| Do a thing
SCHEDULED: <2021-03-26 Fri>
```
The item is scheduled for today (as expected), but it does not get scheduled on future days. If I mark the TODO -> DONE in the agenda, the TODO is closed.

If I do this:

```
* TODO |+1| Do a thing
SCHEDULED: <2021-03-26 Fri +1d>
```
The TODO item appears today in my agenda and every day in the future. What am I missing or forgetting to do?

**Comment by mrcnski** [comment]
For a `+1` task, using the hotkey/command specified in the README will reschedule it to tomorrow.

> The item is scheduled for today (as expected), but it does not get scheduled on future days.

That's not what `org-recur` does. You may be looking for something different, I listed some alternatives in the README.

Feel free to reopen if you have more questions.
