### ISSUE TITLE
Time of day on `|Wkdy|` option

### ISSUE THREAD

**Issue by noghartt** [m-cat/org-recur#7]
I try to put something like it:
```
* |Wkdy 3:00PM| Heading
```

But it generate this timestamp: `SCHEDULED: <2021-10-05 Tue>`. It works correctly only with other options, like `|Mon|`, `|1|`, etc.

**Comment by mrcnski** [comment]
The issue is that `Wkdy` gets expanded to `Mon,Tue,Wed,Thu,Fri` verbatim, so `Wkdy 3:00PM` is expanded to `Mon,Tue,Wed,Thu,Fri 3:00PM` and the time is only applied to Friday. The fix is probably easy for someone more familiar with elisp, but it would take me awhile; not sure when I'll get to it.
